-- EXERCÍCIO 1

SELECT RACES.year, DRIVER.driverId as driver, SUM(DRIVERSTANDINGS.points) AS total_points
FROM DRIVERSTANDINGS
         JOIN RACES ON DRIVERSTANDINGS.raceid = RACES.raceid
         JOIN DRIVER ON DRIVERSTANDINGS.driverId = DRIVER.driverId
GROUP BY RACES.year, DRIVER.driverId
ORDER BY RACES.year DESC, DRIVER.driverid ASC, total_points DESC;
