/* CREATE TABLE */
CREATE TABLE races(
raceId DOUBLE,
year DOUBLE,
round DOUBLE,
circuitId DOUBLE,
name VARCHAR(100),
date VARCHAR(100),
time VARCHAR(100),
url VARCHAR(200),
fp1_date VARCHAR(100),
fp1_time VARCHAR(100),
fp2_date VARCHAR(100),
fp2_time VARCHAR(100),
fp3_date VARCHAR(100),
fp3_time VARCHAR(100),
quali_date VARCHAR(100),
quali_time VARCHAR(100),
sprint_date VARCHAR(100),
sprint_time VARCHAR(100)
);